# test ?
server:
  port: 8888

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: code-odyssey
      authentication-database: admin
      username: ${MONGODB_USER_NAME}
      password: ${MONGODB_USER_PASSWORD}

  rabbitmq:
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    host: localhost
    port: 61613
    queue:
      name: code
    exchange:
      name: code_exchange
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER}

OPENVIDU_URL: ${OPENVIDU_URL}
OPENVIDU_SECRET: ${OPENVIDU_SECRET}